/* tslint:disable:max-line-length */
import HydraClientFactory from "./src/HydraClientFactory";
export default HydraClientFactory;
export { IDictionary } from "./src/IDictionary";
export { IHydraClient } from "./src/IHydraClient";
export { IHypermediaProcessor } from "./src/IHypermediaProcessor";
export { IHypermediaProcessingOptions } from "./src/IHypermediaProcessingOptions";
export { IIriTemplateExpansionStrategy } from "./src/IIriTemplateExpansionStrategy";
export { default as HydraClient } from "./src/HydraClient";
export { HttpCallFacility, HypermediaProcessorFactory } from "./src/HydraClientFactory";
export { default as PartialCollectionCrawler, CrawlingDirection, ICrawlingOptions } from "./src/PartialCollectionCrawler";
export { IApiDocumentation } from "./src/DataModel/IApiDocumentation";
export { IClass } from "./src/DataModel/IClass";
export { ICollection } from "./src/DataModel/ICollection";
export { IHydraResource } from "./src/DataModel/IHydraResource";
export { IHeaders } from "./src/DataModel/IHeaders";
export { IHypermediaContainer } from "./src/DataModel/IHypermediaContainer";
export { IIriTemplate } from "./src/DataModel/IIriTemplate";
export { IIriTemplateMapping } from "./src/DataModel/IIriTemplateMapping";
export { ILink } from "./src/DataModel/ILink";
export { IOperation } from "./src/DataModel/IOperation";
export { IPartialCollectionView } from "./src/DataModel/IPartialCollectionView";
export { IPartialCollectionIterator } from "./src/DataModel/IPartialCollectionIterator";
export { IPointingResource } from "./src/DataModel/IPointingResource";
export { IProperty } from "./src/DataModel/IProperty";
export { IResource } from "./src/DataModel/IResource";
export { ISupportedProperty } from "./src/DataModel/ISupportedProperty";
export { ITemplatedLink } from "./src/DataModel/ITemplatedLink";
export { ITemplatedOperation } from "./src/DataModel/ITemplatedOperation";
export { ITemplatedResource } from "./src/DataModel/ITemplatedResource";
export { IWebResource } from "./src/DataModel/IWebResource";
export { default as FilterableCollection } from "./src/DataModel/Collections/FilterableCollection";
export { default as LinksCollection } from "./src/DataModel/Collections/LinksCollection";
export { default as MappingsCollection } from "./src/DataModel/Collections/MappingsCollection";
export { default as OperationsCollection } from "./src/DataModel/Collections/OperationsCollection";
export { default as ResourceFilterableCollection } from "./src/DataModel/Collections/ResourceFilterableCollection";
export { default as TypesCollection } from "./src/DataModel/Collections/TypesCollection";
export { hydra, rdf, rdfs } from "./src/namespaces";
